name: stock_scan
description: Gestion de stock avec scan

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  barcode_scan2: ^4.5.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fragrancebali-high-resolution-logo-transparent.png